### ISSUE TITLE
Use axios when app is build

### ISSUE THREAD

**Issue by HozSensei** [Deluze/electron-vue-template#28]
Hey !
First thanks for your work, i use your template and it's very usefull !
I have an issue when i use electron + axios. I make some axios request, everything works when i am in dev mod.
But when i build i have 401 error. Is there a fix/trick to make axios works when i build?
I don't know if i explain well my problem ^^'

Thanks !

**Comment by Deluze** [comment]
Glad to hear this project has been helping you. What API are you consuming? From having to guess what you wrote here it could be that some credentials aren't being send/set in your production app.

I don't have enough information to help you with this exact issue, surely axios is being bundled into your app since the request is being made. I suggest adding some logs to your app before making the request to double check if you're sending the correct credentials.

**Comment by HozSensei** [comment]
Wow ! I feel so dumb.. That was the problem. I create a config file. But the path to it was wrong... So now it works. Thanks for your answer and for the projet !
