### ISSUE TITLE
I can't load `.ts` file in another `.ts` file.

### ISSUE THREAD

**Issue by NumberCode** [Deluze/electron-vue-template#33]
Hi Deluze
I'm trying to build a second window(set show=false) to deal with the loading state when reading large files, which causes the interface to become unresponsive.

But now I try to load the corresponding ts (**remote.ts**) file in the html (**remote.html**) file of the second windows, and then encounter these errors when calling other custom files(cross-values.ts) in this **remote.ts** file, I don't know how to solve it, and I haven't found an effective way to check the information.

## If I import the ts script this way, I get this error:

Option 1:
> 
```js
<script type="application/javascript" src="./../main/remote.ts"></script>
```
> <img width="779" alt="image" src="https://user-images.githubusercontent.com/12987627/202838217-46c39ee3-3c23-4bd3-b272-d82155985b37.png">

Option 2:
> 
```js 
<script type="module">require("./../main/remote.ts")</script>
```
> <img width="784" alt="image" src="https://user-images.githubusercontent.com/12987627/202838807-6b58fd29-6eac-4625-b96a-86abdc22f07d.png">

Option 3:
```js
<script type="module" src="./../main/remote.ts"></script>
```
> <img width="780" alt="image" src="https://user-images.githubusercontent.com/12987627/202838997-4030b9c8-cd9a-4965-901e-78995611e8ca.png">

---

remote.ts
<img width="592" alt="image" src="https://user-images.githubusercontent.com/12987627/202838734-fbc9ade2-3965-4abe-a12a-4371f12ab187.png">

cross-values.ts
<img width="515" alt="image" src="https://user-images.githubusercontent.com/12987627/202838341-f6d70773-e42d-49a6-b9e8-c8e2f9265f08.png">

file list.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/12987627/202838291-624b2952-f977-4f87-8ebd-ba7b78fb8ecf.png">

remote.html
<img width="786" alt="image" src="https://user-images.githubusercontent.com/12987627/202838315-3cb3e79e-0220-4254-b969-177254d02829.png">

I have not been able to find the answer to this question in Google, so I would like to ask if you have encountered any similar problems.

**Comment by Deluze** [comment]
The problem is that you're trying to import a module from the renderer that's defined in the main/electron part of your application. I recommend to put all the code referenced by the renderer in the `renderer` directory as these are bundled together, rule of thumb is that your front-end code (`renderer` process) shouldn't know about back-end code (`main` process). Then, option 3 should work.

---

It's clear that option 1 won't ever work; your `remote.ts` _is_ a module, so it needs to be specified as one.

Same is happening in option 2, sort of; you defined the script to be a module, but when you use `require` it assumes the target (`remote.ts`) is not a module. So the proper usage would be

```html
<script module>
import ... from './../main/remote.ts'
</script>
```
I can't see what you're exporting in `remote.ts`, so replace the `...` with whatever fits your code.

Although, fixing option 2 won't be the solution you're looking for and possible won't work out of the box.

**Comment by NumberCode** [comment]
Hi Deluze, thanks for your response!
I tried as you suggested, and put both **remote.html** and **remote.ts** in the renderer directory, and still got this error.
I'm not sure what else could be the cause.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/12987627/202937065-3fc1cc50-1741-4db6-92be-f242228efabe.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/12987627/202937079-9435b80d-f0fa-41b6-bda5-cc80bc0e8494.png">

<img width="787" alt="image" src="https://user-images.githubusercontent.com/12987627/202937276-88ce767a-5973-4e36-bc48-050991fe8867.png">

**Comment by Deluze** [comment]
Can you show me your `build` directory? Seems like your import is incorrect, as you have no default export you should import `ZipCodeValidator` with `import { ZipCodeValidator } from './remote.ts'`

Double check if all paths are as expected in `build`, and is this file being transpiled correctly? Maybe it's still trying to load the ts file from the HTML.

If all looks good, a reproduction repo would be appreciated, hard to tell what's the reason on why you can't import the script.

**Comment by NumberCode** [comment]
@Deluze  Hi Deluze,
I just deleted the `build` folder, which is the newly compiled `build` directory, and it doesn't look like **remote.js** or **remote.html**.

When I moved remote.ts into the main folder, **remote.js** was generated, but now in the **renderer** directory, it is not generated.
And even if **remote.js** is generated under the **main** folder, this error is still displayed.



<img width="474" alt="image" src="https://user-images.githubusercontent.com/12987627/203019480-596e0063-3ac6-4855-bc11-faf8b161790f.png">

**Comment by Deluze** [comment]
That's because electron-builder copies every file that's in the `main` directory and tell the ts compiler to transpile all js files. The renderer works a little bit different, as everything is done through Vite which is running the Vue plugin; it's an SPA and the entry point is only a single html file and ignores the others.

On the dev server, it's likely that the remote.ts is not being transpiled by Vite and that's the reason for error (Vite can't serve you the file). You should be able to check the network log to see what Vite responded with.

I assumed you were transpiling the files already, you might want to look into creating a simple Vite plugin that will also transpile other html/ts files besides Vue, I assume such plugins already exist.

An easier solution might be to utilize Vue router and have your 2nd window go to a specific route.

**Comment by NumberCode** [comment]
Thank you so much! I'm not a front-end engineer, so I lack understanding of many basic knowledge.
Thank you again, based on this great information you told me, I tried to find this link, I will try to follow this configuration after dinner.

https://github.com/vitejs/vite/issues/257
https://stackoverflow.com/questions/68973043/how-to-create-multi-pages-with-vite-following-this-directory-structure
