### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by invaderb** [Deluze/electron-vue-template#8]
Greetings, 

Is there a way to add typescript to this, I tried with the vue cli and was getting errors.

**Comment by rehanvdm** [comment]
Also interested in a TS version. Might fork and attempt to get it working, anyone else working on getting TS support?

**Comment by Deluze** [comment]
Typescript support would be great, PRs are always welcome. I saw more people would be interested in adding typescript to this template.

@rehanvdm let me know if you decide to get it to work, otherwise I'll dive into it in the next 2 weeks :+1:

**Comment by rehanvdm** [comment]
I don't want to make any promises, my plan is to first play around with it, get debugging working etc. Then I will attempt to convert to TS. I also plan on using Vue2 rather than 3, unfortunately Vuetify 3 is still in Alpha and so I don't want to make the jump just yet. Once I am done, I can maybe share what I have? I also don't know how you would switch/choose between the JS version of the template or the TS version?

**Comment by rehanvdm** [comment]
I managed to get a TS version working, far from perfect but might give you an idea of how to do it. Like I mentioned:

**Comment by rehanvdm** [comment]
PS I stuck with Vue3 as Vite and Vue2 does not play well, I rather found a diff framework (planned on using Vuetify but it only had Vue2 support) that is Vue3 and has the components I needed

**Comment by Deluze** [comment]
@rehanvdm seems like you spent quite the time to make it work 😃

I'll check it out soon, I'm currently moving and I don't have access to internet.

About choosing js/ts version of the template, I think I'll make ts the default. I don't plan on making it to hard to use, I want this to stay a Github template too, instead of a Vue generator, or whatever they have nowadays 😅

And I didn't know Vue2 didn't work well with Vite at all.. I used to use Vuetify a lot too 😔 hope you find a good replacement.

**Comment by Deluze** [comment]
@rehanvdm Been working on #10 yesterday, care to try it out?
